wandb_version: 1

epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725030116
    t:
      1:
      - 1
      - 49
      - 55
      2:
      - 1
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
